name: Generate reading list

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  generate-reading-list:
    runs-on: ubuntu-slim
    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-go@v6
        with:
          go-version-file: .tool-versions
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go mod download

      - name: Generate reading list
        run: go run reading.go

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/content/reading.md
          git diff --staged --quiet || git commit -m "chore: update reading list"
          git push
